### ISSUE TITLE
Install on x64 system

### ISSUE THREAD

**Issue by kinh-nguyen** [aitjcize/Qwertickle#4]
Are there anyway to tackle this?

**Comment by aitjcize** [comment]
What problem do you have when installing on x86_64?

**Comment by kinh-nguyen** [comment]
Sorry for the unclear report!
I'm using eOS ~ Ubuntu precise 64. Installing Qwertickle requires a lot of i386 libraries. 
I know that I can install additional x86 libs but this will lead to breaking the system, or conflict with some softwares, themes...one way or another. 
My  question is whether we can have a x64 version of this.

**Comment by aitjcize** [comment]
Did you install it from the PPA? If you build it from source, it requires only 64-bit libraries.

**Comment by kinh-nguyen** [comment]
Hi, indeed, I compiled from source and it works. But after restarted, at first there's nothing happen, even the icon.

**Comment by aitjcize** [comment]
@nguyenkinh can you provide more details? What distribution are you using?

**Comment by kinh-nguyen** [comment]
I'm using elementary os - which is based on Ubuntu Precise, but using its
own Pantheon shell, switchboard and apps.

**Comment by aitjcize** [comment]
Are there any error messages in the console when you executed it?

**Comment by kinh-nguyen** [comment]
I'm not sure , it _does_ work now, but last time when I compiled it the
first few times it didn't work and then I gave up. Then the next day it
just shows up. You can close this now.
Thanks.

**Comment by aitjcize** [comment]
Thanks for the report anyway :)
